/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import connect.ConnectDB;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import security.EncodeAES;

/**
 *
 * @author Hung Tun
 */
public class ClientView extends javax.swing.JFrame {

    /**
     * Creates new form ClientView
     */
    public Login login = new Login();
    private String host;
    private int port;
    public static Socket client;
    private EncodeAES encodeAES = new EncodeAES();

    public ClientView() {

        initComponents();
        jtanoidung.setEditable(false);
        txt_chat.requestFocusInWindow();
        jl_username.setText("Username: " + login.acount.getUsername());

        Client();
    }

    public void Client() {

        try {
            client = new Socket("localhost", login.acount.getPort());
            new Thread(new Received(client.getInputStream())).start();
        } catch (IOException ex) {
            Logger.getLogger(ClientView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtanoidung = new javax.swing.JTextArea();
        txt_chat = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        btn_leave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_username.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N

        jtanoidung.setColumns(20);
        jtanoidung.setRows(5);
        jScrollPane1.setViewportView(jtanoidung);

        txt_chat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_chatKeyPressed(evt);
            }
        });

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        btn_leave.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btn_leave.setText("Leave group");
        btn_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_leave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_send))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_leave, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        String s = encodeAES.encrypt(txt_chat.getText().trim());
        String username = encodeAES.encrypt(login.acount.getUsername().trim());
        send(username, s);
        txt_chat.setText("");
    }//GEN-LAST:event_btn_sendActionPerformed
    public void send(String username, String s) {

        try {
            PrintStream output = new PrintStream(client.getOutputStream());
            output.println(username);
            output.println(s);
        } catch (IOException ex) {
            Logger.getLogger(ClientView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btn_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leaveActionPerformed

        try {
            // TODO add your handling code here:
            PrintStream output = new PrintStream(client.getOutputStream());

            String s = encodeAES.encrypt("EXIT!");// đã rời khỏi cuộc trò chuyện!
            String username = encodeAES.encrypt(login.acount.getUsername());
            output.println(username);
            output.println(s);
        } catch (IOException ex) {
            Logger.getLogger(ClientView.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btn_leaveActionPerformed

    private void txt_chatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_chatKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String s = encodeAES.encrypt(txt_chat.getText().trim());
            String username = encodeAES.encrypt(login.acount.getUsername().trim());
            send(username, s);
            txt_chat.setText("");
        }

    }//GEN-LAST:event_txt_chatKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ClientView().setVisible(true);
                ClientView client = new ClientView();
                client.setLocationRelativeTo(null);
                client.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_leave;
    private javax.swing.JButton btn_send;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_username;
    private javax.swing.JTextArea jtanoidung;
    private javax.swing.JTextField txt_chat;
    // End of variables declaration//GEN-END:variables

    class Received implements Runnable {

        private InputStream server;

        public Received(InputStream server) {
            this.server = server;
        }

        @Override
        public void run() {
            Scanner s = new Scanner(server);
            while (s.hasNextLine()) {
                String name = login.acount.getUsername().trim();
                String username = encodeAES.decrypt(s.nextLine().trim());
                String message = encodeAES.decrypt(s.nextLine().trim());
                System.out.println("Username: " + username);
                System.out.println("Message: " + message);
                if (message.equals("EXIT!")) {
                    String s1 = "đã rời khỏi phòng chat!";
                    jtanoidung.append(username + " " + s1 + "\n");
                } else if (message.equals("JOIN!")) {
                    String s1 = "đã tham gia phòng chat!";
                    jtanoidung.append(username + " " + s1 + "\n");
                } else {
                    if (name.equals(username)) {
                        jtanoidung.append("Me: " + message + "\n");

                    } else {
                        jtanoidung.append(username + ": " + message + "\n");
                        jtanoidung.setToolTipText(username);
                    }
                }
            }
        }
    }
}
